# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-03-22 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('colegiobd', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='prof_id',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='dep_id',
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Profesor',
        ),
    ]
